import java.util.Scanner;//input.
public class patternPrinting1 {// class Starting point...
    public static void main(String[] args) { // publicStaticVoidMain Starting point...
        Scanner scanner = new Scanner(System.in); //input.

        System.out.print("Enter the value of n: ");//input.
        int n = scanner.nextInt(); //input.

        for (int i = 1; i <= n; i++) { // loop starting point
            for (int j = 1; j <= n; j++) {
                if (i == 1 || i == n || j == 1 || j == n) {
                    System.out.print("1 "); //printing 1...
                    } else {
                        System.out.print("0 "); //printing 0...
                    }
            }
                System.out.println();
        } //loop ending point...

    } // publicStaticVoidMain Ending point...
} // class Ending point...

